services:
  # OpenSearch Service
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - plugins.security.disabled=true
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=T!mberW0lf#92"
      - compatibility.override_main_response_version=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - logging-net

  # OpenSearch Dashboards Service
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"
    networks:
      - logging-net

  # Log Generator Service
  loggenerator:
    build:
      context: .
      dockerfile: Dockerfile.loggenerator
    container_name: loggenerator
    labels:
      filebeat_log_gathering: enabled
    networks:
      - logging-net

  # Filebeat Service
  filebeat:
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    container_name: filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - logging-net
    depends_on:
      - opensearch

networks:
  logging-net:
    driver: bridge

volumes:
  opensearch-data:
