# Newer versions of filebeat don't recognize OpenSearch.
# We also need to use the OSS version, otherwise OpenSearch is still not recognized.
FROM docker.elastic.co/beats/filebeat-oss:7.10.2

WORKDIR /usr/share/filebeat

COPY filebeat.yml /usr/share/filebeat/filebeat.yml
USER root

# If filebeat.yml isn't set to root, filebeat will complain at startup and exit.
RUN chown root:root /usr/share/filebeat/filebeat.yml && chmod 600 /usr/share/filebeat/filebeat.yml

ENTRYPOINT ["filebeat", "-e"]
