# Temp
logging.level: debug
logging.selectors: ["*"]

filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  json.message_key: log
  json.keys_under_root: true
  processors:
    - add_docker_metadata: ~
    - rename:
        fields:
          - from: "@t"
            to: "timestamp"
          - from: "@mt"
            to: "message"
    - drop_event:
        when:
          not:
            contains:
              docker.container.labels.filebeat_log_gathering: enabled

output.elasticsearch:
  hosts: ["http://opensearch:9200"]
  username: "admin"
  password: "admin"
