filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            equals:
              docker.container.labels.filebeat_log_gathering: "enabled"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              json.message_key: log
              json.keys_under_root: true
              json.add_error_key: false
              processors:
                - add_docker_metadata: ~
                - timestamp:
                    field: "@t"
                    layouts:
                      - "2024-08-16T14:02:59.7059876Z"
                - drop_fields:
                    fields: ["@t"]

output.elasticsearch:
  hosts: ["https://opensearch-node1:9200", "https://opensearch-node2:9200"]
  username: "admin"
  password: "T!mberW0lf#92"
  ssl.verification_mode: none